apiVersion: v1
kind: Service
metadata:
  name: jielabs-backend
  labels:
    app: jielabs-backend
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: jielabs-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jielabs-backend
  labels:
    app: jielabs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jielabs-backend
  template:
    metadata:
      labels:
        app: jielabs-backend
    spec:
      containers:
        - name: jielabs-backend
          image: jiegec/jielabs-backend:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: "1"
          envFrom:
           - configMapRef:
               name: jielabs-backend-env

